@host = http://localhost:3000
@urlUsuarios = /api/user
@urlCursos = /api/courses
@urlUpload = /api/upload
@urlChat = /api/chat
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiUHJvZmVzb3IiLCJleHAiOjE3NDk0OTQyODIsImlhdCI6MTc0ODg4OTQ4Mn0.sVRJ2J5hDZ2ae3eohqdfE3Ec482TkYyn-0xlZYEKbro

### USER ###

POST {{host}}{{urlUsuarios}}/login
Content-Type: application/json

{ 
"email": "fran@mail.es",
"password": "1234"
}

###
POST {{host}}{{urlUsuarios}}/register
Content-Type: application/json

{
    "name":"Fran",
    "email": "fran@mail.es",
    "password": "1234",
    "role": "Profesor"
}

### CURSOS ###

POST {{host}}{{urlCursos}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Matemáticas I",
  "description": "Aritmética"
}

### SUBIDA DE DOCUMENTO ###

POST {{host}}{{urlUpload}}/1
Authorization: Bearer {{token}}

@document=file://Users/fran/Desktop/PlanEmpresa.pdf

### ENVIAR MENSAJE AL ASISTENTE ###
POST {{host}}{{urlChat}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "message": "¿Qué temas se abordan en este curso?"
}

### OBTENER HISTORIAL ###
GET {{host}}{{urlChat}}/1/history
Authorization: Bearer {{token}}

