@host = http://localhost:3000
@urlUsuarios = /api/user
@urlCursos = /api/courses
@urlUpload = /api/upload

### USER ###

POST {{host}}{{urlUsuarios}}/login
Content-Type: application/json

{ 
"email": "fran@mail.es",
"password": "1234"
}

###
POST {{host}}{{urlUsuarios}}/register
Content-Type: application/json

{
    "name":"Fran",
    "email": "fran@mail.es",
    "password": "1234",
    "role": "Profesor"
}

### CURSOS ###

POST {{host}}{{urlCursos}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiUHJvZmVzb3IiLCJleHAiOjE3NDk0OTQyODIsImlhdCI6MTc0ODg4OTQ4Mn0.sVRJ2J5hDZ2ae3eohqdfE3Ec482TkYyn-0xlZYEKbro

{
  "name": "Matemáticas I",
  "description": "Aritmética"
}

### SUBIDA DE DOCUMENTO ###

POST {{host}}{{urlUpload}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiUHJvZmVzb3IiLCJleHAiOjE3NDk0OTQyODIsImlhdCI6MTc0ODg4OTQ4Mn0.sVRJ2J5hDZ2ae3eohqdfE3Ec482TkYyn-0xlZYEKbro

@document=file://Users/fran/Desktop/PlanEmpresa.pdf
